### ISSUE TITLE
Discussion: complete callback on an array of scripts to load

### ISSUE THREAD

**Issue by jlchereau** [SlexAxton/yepnope.js#219]
How do you recommend we should implement a complete callback on an array of scripts to load, which was a feature of version 1.5 and which does not seem to be fulfilled by version 2.0? Thx.

**Comment by SlexAxton** [comment]
The goal of the 2.0 version was to remove the ability to load multiple scripts, as a performance best-practice. If you want multiple scripts you can use the 1.x versions, but I don't recommend it. Lots of good build tools out there these days!
