### ISSUE TITLE
Ordering of arguments

### ISSUE THREAD

**Issue by BurntCaramel** [SlexAxton/yepnope.js#220]
From the example in the README:
```JavaScript
yepnope('script.js', {
  modernimages: Modernizr.webp && Modernizr.apng,
  css3: Modernizr.borderradius && Modernizr.boxshadow,
  consoleapis: window.console && window.console.log
});
```
The requested URL will be `script.js?yep=css3,consoleapis&nope=modernimages`. One browser may decide to put `css3` before `consoleapis` and one the other way. Of course you can customize this yourself, but by default the order of the arguments will be up to how the browser decides to loop through the properties in `for(var testname in tests)`? See http://stackoverflow.com/questions/280713/elements-order-in-a-for-in-loop – it’s not in the spec what order these are in. It does seem to be that all browsers basically have a consistent order, though, so perhaps that is enough for a small script like this.

In regards to the general yepnope 2.0 change – interesting to see how the best practices of the web keep evolving!

**Comment by SlexAxton** [comment]
I wouldn't worry about the order too much in practice, but I suppose I was assuming a dynamic server would interpret the query parameters  and return the correct file (and then cache that result). I don't think it'd be worth it to sort or anything unless someone comes across some actual issues here.

Appreciate the valid input, though!
