### ISSUE TITLE
Load array in version 2.0

### ISSUE THREAD

**Issue by rhernandog** [SlexAxton/yepnope.js#222]
Hi,

I'd like to know if it's possible to load an array of files like in version 1.5:

```javascript
yepnope(["file1.js","file2.js","file3.css"], {}, function(){
  //callback code
});
```

I don't care about the loading order, all I need is a callback once all the files are loaded.

Thanks,
Rodrigo.

**Comment by SlexAxton** [comment]
The goal of yepnope 2 is to avoid loading multiple files like this. If you'd like this functionality, then use yepnope 1.x, but it may come with performance costs.
