### ISSUE TITLE
Can I still load a JS file based on a test?

### ISSUE THREAD

**Issue by iq-dot** [SlexAxton/yepnope.js#227]
Hi guys,

With regards to the new version I am not sure from the documentation if I can still load a single javascript file based on a test? I have not used the old yepnope.js and I basically came from an example to load the 'Intl.js' library based on whether 'Window.Intl' exists.

I was going to do something like this:

```
yepnope({
  test : window.Intl,
  nope : ['js/intl.js']
});
```

Though the new documentation doesn't seem to have this format. Is something like that still supported?

Thanks

**Comment by SlexAxton** [comment]
It was leading to some pretty ugly stuff. Your use case is fine, but an if statement works just as nicely:

```js
if (window.Intl) yepnope.injectJs('js/intl.js');
```

The `IntlPolyfill` should probably recommend a different method than they currently are. The actual nicer scenario is bundling `intl.js` with your main build for users that need it:

```js
yepnope('js/app.js', {
  intl: window.Intl
}, function() {
  console.log(new Intl.DateTimeFormat(...).format(new Date());
});
```

This would request either: `js/app.js?yep=intl` or `js/app.js?nope=intl`

You could then potentially handle serving the correct file depending on those urls (which can look different with a different formatter).

Hope that helps!

**Comment by iq-dot** [comment]
Brilliant thanks for the alternative.
